### ISSUE TITLE
Research: Docker and containerization. How to use it with Github Actions.

### ISSUE THREAD

**Issue by savin000** [VSU-CS-MCS/user-service#7]
Also find info about Dockerfile, Docker-compose

**Comment by Mr-Keltt** [comment]
**Docker and containerization** - are technologies that allow you to package applications and their dependencies into a single container that can be run on any machine that supports Docker. This makes it easier to deploy the application and simplifies the dependency management process.
**Github Actions** - is an automation system for Github that allows you to create and run scripts and actions based on Github events, such as creating a pool request or commit to a repository.
Docker can be used with Github Actions to automate the process of building, testing and deploying containerized applications. To do this, you need to create a Github Actions configuration file in the repository, which will contain the steps to launch Docker containers.
For example, in the configuration file, you can use the "checkout" step to clone the repository, then use the "docker build" step to build the Docker image from Dockerfile, and then use the "docker run" step to launch the container and run tests. If the tests are successful, you can use other steps, such as "docker push" to upload the image to the Docker registry and "docker deploy" to deploy the container on the host system.


**Dockerfile** - is a file that is used to automate the process of building a Docker image. It contains instructions that the Docker Engine executes one by one to create an image that can be used to run containers. In general, the Dockerfile contains the following elements:

• Base Image: Dockerfile starts with an instruction that specifies the base image on which a new image will be created. The base image contains the operating system and all the dependencies that are necessary for the application to work.
• Instructions: Next in the Dockerfile are instructions that are executed alternately and add new layers to the image. Instructions may include commands for installing packages, creating directories, copying files, and more.
• Comments: A dockerfile can contain comments that help describe what each instruction does. Comments start with the # character and are ignored by the Docker Engine.

Here are some examples of instructions that can be used in Dockerfile:
• FROM: specifies the base image
• RUN: executes a command inside the container
• COPY: copies files from the host system to the image
• ADD: Copies files from the host system to the image, but can also extract files from archives and URLs
• WORKDIR: Sets the working directory for subsequent instructions
• EXPOSE: specifies the ports that the container should open
• CMD: sets the default command to be executed when the container is started
To create an image from a Dockerfile, you need to run the "docker build" command with the path to the Dockerfile. This command will start building the Docker image based on the instructions contained in the Dockerfile. The result will be a new image that can be used to launch containers.


**Docker-compose** - is a tool for managing Docker containers and coordinating the many containers required for an application to work. It allows you to define, configure and run many related containers simultaneously using a YAML configuration file.
Docker-compose simplifies the process of managing a variety of containers necessary for the development and testing of an application, as well as for deploying an application in production. It allows you to combine several containers into one group, the so-called service, and manage them using a single configuration file.
To work with Docker-compose, you need to create a configuration file in YAML format. In this file, you define the services required for your application to work, as well as their dependencies and configuration parameters.

**Comment by Mr-Keltt** [comment]
[Docker.docx](https://github.com/VSU-CS-MCS/user-service/files/10834313/Docker.docx)
